Excluded:
  - src/twilio/api/default_api.cr
  - bin
  - lib
  - local
Documentation/DocumentationAdmonition:
  Enabled: false
Lint/NotNil:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
