tasks:
  - name: 'Update models'
    file_glob: './src/twilio/models/*cr'
    changes:
      -
        name: 'Correct datetime converter'
        pattern: 'Time::RFC3339Converter'
        new_value: 'Time::RFC2822Converter'
  - name: 'Update apis'
    file_glob: './src/twilio/api/*cr'
    changes:
      -
        name: 'Update account_sid param'
        pattern: '\*, account_sid : String'
        new_value: '*, account_sid : String = @account_sid'
      -
        name: 'Correct datetime formatting'
        pattern: 'Time::Format::RFC_3339'
        new_value: 'Time::Format::RFC_2822'
      -
        name: 'Update api initializer'
        pattern: '$\n^    def initialize\(api_client = ApiClient.default\)$\n^      @api_client = api_client$'
        new_value: "
          \   property account_sid : String\n\n
          \   def initialize(api_client = ApiClient.default)\n
          \     @api_client = api_client\n
          \     @account_sid = api_client.config.username.not_nil!"
        multi_line: true
