#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"
require "../../src/twilio/api/keys_api"

# Unit tests for Twilio::KeysApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "KeysApi" do
  describe "test an instance of KeysApi" do
    it "should create an instance of KeysApi" do
      api_instance = Twilio::KeysApi.new
      api_instance.should be_a(Twilio::KeysApi)
    end
  end

  # unit tests for create_new_key
  #
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will be responsible for the new Key resource.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :friendly_name A descriptive string that you create to describe the resource. It can be up to 64 characters long.
  # @return [NewKey]
  describe "create_new_key test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for delete_key
  #
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Key resources to delete.
  # @param sid The Twilio-provided string that uniquely identifies the Key resource to delete.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "delete_key test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for fetch_key
  #
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Key resource to fetch.
  # @param sid The Twilio-provided string that uniquely identifies the Key resource to fetch.
  # @param [Hash] opts the optional parameters
  # @return [Key]
  describe "fetch_key test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for list_key
  #
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Key resources to read.
  # @param [Hash] opts the optional parameters
  # @option opts [Int32] :page_size How many resources to return in each list page. The default is 50, and the maximum is 1000.
  # @return [ListKeyResponse]
  describe "list_key test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for update_key
  #
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Key resources to update.
  # @param sid The Twilio-provided string that uniquely identifies the Key resource to update.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :friendly_name A descriptive string that you create to describe the resource. It can be up to 64 characters long.
  # @return [Key]
  describe "update_key test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
