#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"
require "../../src/twilio/api/recordings_api"

# Unit tests for Twilio::RecordingsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "RecordingsApi" do
  describe "test an instance of RecordingsApi" do
    it "should create an instance of RecordingsApi" do
      api_instance = Twilio::RecordingsApi.new
      api_instance.should be_a(Twilio::RecordingsApi)
    end
  end

  # unit tests for delete_recording
  # Delete a recording from your account
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Recording resources to delete.
  # @param sid The Twilio-provided string that uniquely identifies the Recording resource to delete.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "delete_recording test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for delete_recording_add_on_result
  # Delete a result and purge all associated Payloads
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Recording AddOnResult resources to delete.
  # @param reference_sid The SID of the recording to which the result to delete belongs.
  # @param sid The Twilio-provided string that uniquely identifies the Recording AddOnResult resource to delete.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "delete_recording_add_on_result test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for delete_recording_add_on_result_payload
  # Delete a payload from the result along with all associated Data
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Recording AddOnResult Payload resources to delete.
  # @param reference_sid The SID of the recording to which the AddOnResult resource that contains the payloads to delete belongs.
  # @param add_on_result_sid The SID of the AddOnResult to which the payloads to delete belongs.
  # @param sid The Twilio-provided string that uniquely identifies the Recording AddOnResult Payload resource to delete.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "delete_recording_add_on_result_payload test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for delete_recording_transcription
  #
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Transcription resources to delete.
  # @param recording_sid The SID of the [Recording](https://www.twilio.com/docs/voice/api/recording) that created the transcription to delete.
  # @param sid The Twilio-provided string that uniquely identifies the Transcription resource to delete.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "delete_recording_transcription test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for fetch_recording
  # Fetch an instance of a recording
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Recording resource to fetch.
  # @param sid The Twilio-provided string that uniquely identifies the Recording resource to fetch.
  # @param [Hash] opts the optional parameters
  # @option opts [Bool] :include_soft_deleted A boolean parameter indicating whether to retrieve soft deleted recordings or not. Recordings metadata are kept after deletion for a retention period of 40 days.
  # @return [Recording]
  describe "fetch_recording test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for fetch_recording_add_on_result
  # Fetch an instance of an AddOnResult
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Recording AddOnResult resource to fetch.
  # @param reference_sid The SID of the recording to which the result to fetch belongs.
  # @param sid The Twilio-provided string that uniquely identifies the Recording AddOnResult resource to fetch.
  # @param [Hash] opts the optional parameters
  # @return [RecordingRecordingAddOnResult]
  describe "fetch_recording_add_on_result test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for fetch_recording_add_on_result_payload
  # Fetch an instance of a result payload
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Recording AddOnResult Payload resource to fetch.
  # @param reference_sid The SID of the recording to which the AddOnResult resource that contains the payload to fetch belongs.
  # @param add_on_result_sid The SID of the AddOnResult to which the payload to fetch belongs.
  # @param sid The Twilio-provided string that uniquely identifies the Recording AddOnResult Payload resource to fetch.
  # @param [Hash] opts the optional parameters
  # @return [RecordingRecordingAddOnResultRecordingAddOnResultPayload]
  describe "fetch_recording_add_on_result_payload test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for fetch_recording_transcription
  #
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Transcription resource to fetch.
  # @param recording_sid The SID of the [Recording](https://www.twilio.com/docs/voice/api/recording) that created the transcription to fetch.
  # @param sid The Twilio-provided string that uniquely identifies the Transcription resource to fetch.
  # @param [Hash] opts the optional parameters
  # @return [Transcription]
  describe "fetch_recording_transcription test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for list_recording
  # Retrieve a list of recordings belonging to the account used to make the request
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Recording resources to read.
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :date_created Only include recordings that were created on this date. Specify a date as &#x60;YYYY-MM-DD&#x60; in GMT, for example: &#x60;2009-07-06&#x60;, to read recordings that were created on this date. You can also specify an inequality, such as &#x60;DateCreated&lt;&#x3D;YYYY-MM-DD&#x60;, to read recordings that were created on or before midnight of this date, and &#x60;DateCreated&gt;&#x3D;YYYY-MM-DD&#x60; to read recordings that were created on or after midnight of this date.
  # @option opts [Time] :date_created2 Only include recordings that were created on this date. Specify a date as &#x60;YYYY-MM-DD&#x60; in GMT, for example: &#x60;2009-07-06&#x60;, to read recordings that were created on this date. You can also specify an inequality, such as &#x60;DateCreated&lt;&#x3D;YYYY-MM-DD&#x60;, to read recordings that were created on or before midnight of this date, and &#x60;DateCreated&gt;&#x3D;YYYY-MM-DD&#x60; to read recordings that were created on or after midnight of this date.
  # @option opts [Time] :date_created3 Only include recordings that were created on this date. Specify a date as &#x60;YYYY-MM-DD&#x60; in GMT, for example: &#x60;2009-07-06&#x60;, to read recordings that were created on this date. You can also specify an inequality, such as &#x60;DateCreated&lt;&#x3D;YYYY-MM-DD&#x60;, to read recordings that were created on or before midnight of this date, and &#x60;DateCreated&gt;&#x3D;YYYY-MM-DD&#x60; to read recordings that were created on or after midnight of this date.
  # @option opts [String] :call_sid The [Call](https://www.twilio.com/docs/voice/api/call-resource) SID of the resources to read.
  # @option opts [String] :conference_sid The Conference SID that identifies the conference associated with the recording to read.
  # @option opts [Bool] :include_soft_deleted A boolean parameter indicating whether to retrieve soft deleted recordings or not. Recordings metadata are kept after deletion for a retention period of 40 days.
  # @option opts [Int32] :page_size How many resources to return in each list page. The default is 50, and the maximum is 1000.
  # @return [ListRecordingResponse]
  describe "list_recording test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for list_recording_add_on_result
  # Retrieve a list of results belonging to the recording
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Recording AddOnResult resources to read.
  # @param reference_sid The SID of the recording to which the result to read belongs.
  # @param [Hash] opts the optional parameters
  # @option opts [Int32] :page_size How many resources to return in each list page. The default is 50, and the maximum is 1000.
  # @return [ListRecordingAddOnResultResponse]
  describe "list_recording_add_on_result test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for list_recording_add_on_result_payload
  # Retrieve a list of payloads belonging to the AddOnResult
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Recording AddOnResult Payload resources to read.
  # @param reference_sid The SID of the recording to which the AddOnResult resource that contains the payloads to read belongs.
  # @param add_on_result_sid The SID of the AddOnResult to which the payloads to read belongs.
  # @param [Hash] opts the optional parameters
  # @option opts [Int32] :page_size How many resources to return in each list page. The default is 50, and the maximum is 1000.
  # @return [ListRecordingAddOnResultPayloadResponse]
  describe "list_recording_add_on_result_payload test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for list_recording_transcription
  #
  # @param account_sid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Transcription resources to read.
  # @param recording_sid The SID of the [Recording](https://www.twilio.com/docs/voice/api/recording) that created the transcriptions to read.
  # @param [Hash] opts the optional parameters
  # @option opts [Int32] :page_size How many resources to return in each list page. The default is 50, and the maximum is 1000.
  # @return [ListRecordingTranscriptionResponse]
  describe "list_recording_transcription test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
