#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Twilio::Application
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Twilio::Application do
  describe "test an instance of Application" do
    it "should create an instance of Application" do
      # instance = Twilio::Application.new
      # (instance).should be_a(Twilio::Application)
    end
  end

  describe "test attribute 'account_sid'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'api_version'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'date_created'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'date_updated'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'friendly_name'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'message_status_callback'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'sid'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'sms_fallback_method'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'sms_fallback_url'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'sms_method'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'sms_status_callback'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'sms_url'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'status_callback'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'status_callback_method'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'uri'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'voice_caller_id_lookup'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'voice_fallback_method'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'voice_fallback_url'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'voice_method'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'voice_url'" do
    it "should work" do
      # instance = Twilio::Application.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
