#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Twilio::CallCallEventRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Twilio::CallCallEventRequest do
  describe "test an instance of CallCallEventRequest" do
    it "should create an instance of CallCallEventRequest" do
      # instance = Twilio::CallCallEventRequest.new
      # (instance).should be_a(Twilio::CallCallEventRequest)
    end
  end

  describe "test attribute 'method'" do
    it "should work" do
      # instance = Twilio::CallCallEventRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'url'" do
    it "should work" do
      # instance = Twilio::CallCallEventRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'parameters'" do
    it "should work" do
      # instance = Twilio::CallCallEventRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
