#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Twilio::CallCallEvent
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Twilio::CallCallEvent do
  describe "test an instance of CallCallEvent" do
    it "should create an instance of CallCallEvent" do
      # instance = Twilio::CallCallEvent.new
      # (instance).should be_a(Twilio::CallCallEvent)
    end
  end

  describe "test attribute 'request'" do
    it "should work" do
      # instance = Twilio::CallCallEvent.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'response'" do
    it "should work" do
      # instance = Twilio::CallCallEvent.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
