#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Twilio::IncomingPhoneNumberMobileEnumVoiceReceiveMode
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Twilio::IncomingPhoneNumberMobileEnumVoiceReceiveMode do
  describe "test an instance of IncomingPhoneNumberMobileEnumVoiceReceiveMode" do
    it "should create an instance of IncomingPhoneNumberMobileEnumVoiceReceiveMode" do
      # instance = Twilio::IncomingPhoneNumberMobileEnumVoiceReceiveMode.new
      # (instance).should be_a(Twilio::IncomingPhoneNumberMobileEnumVoiceReceiveMode)
    end
  end
end
