#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Twilio::ListSipIpAccessControlListResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Twilio::ListSipIpAccessControlListResponse do
  describe "test an instance of ListSipIpAccessControlListResponse" do
    it "should create an instance of ListSipIpAccessControlListResponse" do
      # instance = Twilio::ListSipIpAccessControlListResponse.new
      # (instance).should be_a(Twilio::ListSipIpAccessControlListResponse)
    end
  end

  describe "test attribute '_end'" do
    it "should work" do
      # instance = Twilio::ListSipIpAccessControlListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'first_page_uri'" do
    it "should work" do
      # instance = Twilio::ListSipIpAccessControlListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'ip_access_control_lists'" do
    it "should work" do
      # instance = Twilio::ListSipIpAccessControlListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'next_page_uri'" do
    it "should work" do
      # instance = Twilio::ListSipIpAccessControlListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'page'" do
    it "should work" do
      # instance = Twilio::ListSipIpAccessControlListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'page_size'" do
    it "should work" do
      # instance = Twilio::ListSipIpAccessControlListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'previous_page_uri'" do
    it "should work" do
      # instance = Twilio::ListSipIpAccessControlListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'start'" do
    it "should work" do
      # instance = Twilio::ListSipIpAccessControlListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'uri'" do
    it "should work" do
      # instance = Twilio::ListSipIpAccessControlListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
