#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Twilio::NotificationInstance
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Twilio::NotificationInstance do
  describe "test an instance of NotificationInstance" do
    it "should create an instance of NotificationInstance" do
      # instance = Twilio::NotificationInstance.new
      # (instance).should be_a(Twilio::NotificationInstance)
    end
  end

  describe "test attribute 'account_sid'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'api_version'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'call_sid'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'date_created'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'date_updated'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'error_code'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'log'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'message_date'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'message_text'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'more_info'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'request_method'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'request_url'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'request_variables'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'response_body'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'response_headers'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'sid'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'uri'" do
    it "should work" do
      # instance = Twilio::NotificationInstance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
