#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Twilio::Queue
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Twilio::Queue do
  describe "test an instance of Queue" do
    it "should create an instance of Queue" do
      # instance = Twilio::Queue.new
      # (instance).should be_a(Twilio::Queue)
    end
  end

  describe "test attribute 'account_sid'" do
    it "should work" do
      # instance = Twilio::Queue.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'average_wait_time'" do
    it "should work" do
      # instance = Twilio::Queue.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'current_size'" do
    it "should work" do
      # instance = Twilio::Queue.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'date_created'" do
    it "should work" do
      # instance = Twilio::Queue.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'date_updated'" do
    it "should work" do
      # instance = Twilio::Queue.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'friendly_name'" do
    it "should work" do
      # instance = Twilio::Queue.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'max_size'" do
    it "should work" do
      # instance = Twilio::Queue.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'sid'" do
    it "should work" do
      # instance = Twilio::Queue.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'uri'" do
    it "should work" do
      # instance = Twilio::Queue.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
