#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Twilio::UsageRecordYesterdayEnumCategory
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Twilio::UsageRecordYesterdayEnumCategory do
  describe "test an instance of UsageRecordYesterdayEnumCategory" do
    it "should create an instance of UsageRecordYesterdayEnumCategory" do
      # instance = Twilio::UsageRecordYesterdayEnumCategory.new
      # (instance).should be_a(Twilio::UsageRecordYesterdayEnumCategory)
    end
  end
end
