#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Twilio::UsageUsageRecord
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Twilio::UsageUsageRecord do
  describe "test an instance of UsageUsageRecord" do
    it "should create an instance of UsageUsageRecord" do
      # instance = Twilio::UsageUsageRecord.new
      # (instance).should be_a(Twilio::UsageUsageRecord)
    end
  end

  describe "test attribute 'account_sid'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'api_version'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'as_of'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'category'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'count'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'count_unit'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'description'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'end_date'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'price'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'price_unit'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'start_date'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'subresource_uris'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'uri'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'usage'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'usage_unit'" do
    it "should work" do
      # instance = Twilio::UsageUsageRecord.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
