#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Twilio::UsageRecordDailyEnumCategory
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Twilio::UsageRecordDailyEnumCategory do
  describe "test an instance of UsageRecordDailyEnumCategory" do
    it "should create an instance of UsageRecordDailyEnumCategory" do
      # instance = Twilio::UsageRecordDailyEnumCategory.new
      # (instance).should be_a(Twilio::UsageRecordDailyEnumCategory)
    end
  end
end
