#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module Twilio
  class Account
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Optional Properties

    # The authorization token for this account
    @[JSON::Field(key: "auth_token", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: auth_token.nil? && !auth_token_present?)]
    getter auth_token : String? = nil

    @[JSON::Field(ignore: true)]
    property? auth_token_present : Bool = false

    # The date this account was created
    @[JSON::Field(key: "date_created", type: Time?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: date_created.nil? && !date_created_present?, converter: Time::RFC2822Converter)]
    getter date_created : Time? = nil

    @[JSON::Field(ignore: true)]
    property? date_created_present : Bool = false

    # The date this account was last updated
    @[JSON::Field(key: "date_updated", type: Time?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: date_updated.nil? && !date_updated_present?, converter: Time::RFC2822Converter)]
    getter date_updated : Time? = nil

    @[JSON::Field(ignore: true)]
    property? date_updated_present : Bool = false

    # A human readable description of this account
    @[JSON::Field(key: "friendly_name", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: friendly_name.nil? && !friendly_name_present?)]
    getter friendly_name : String? = nil

    @[JSON::Field(ignore: true)]
    property? friendly_name_present : Bool = false

    # The unique 34 character id representing the parent of this account
    @[JSON::Field(key: "owner_account_sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: owner_account_sid.nil? && !owner_account_sid_present?)]
    getter owner_account_sid : String? = nil
    MAX_LENGTH_FOR_OWNER_ACCOUNT_SID = 34
    MIN_LENGTH_FOR_OWNER_ACCOUNT_SID = 34
    PATTERN_FOR_OWNER_ACCOUNT_SID    = /^AC[0-9a-fA-F]{32}$/

    @[JSON::Field(ignore: true)]
    property? owner_account_sid_present : Bool = false

    # A 34 character string that uniquely identifies this resource.
    @[JSON::Field(key: "sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: sid.nil? && !sid_present?)]
    getter sid : String? = nil
    MAX_LENGTH_FOR_SID = 34
    MIN_LENGTH_FOR_SID = 34
    PATTERN_FOR_SID    = /^AC[0-9a-fA-F]{32}$/

    @[JSON::Field(ignore: true)]
    property? sid_present : Bool = false

    @[JSON::Field(key: "status", type: Twilio::AccountEnumStatus?, default: nil, required: false, nullable: false, emit_null: false)]
    getter status : Twilio::AccountEnumStatus? = nil

    @[JSON::Field(key: "subresource_uris", type: Hash(String, String)?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: subresource_uris.nil? && !subresource_uris_present?)]
    getter subresource_uris : Hash(String, String)? = nil

    @[JSON::Field(ignore: true)]
    property? subresource_uris_present : Bool = false

    @[JSON::Field(key: "type", type: Twilio::AccountEnumType?, default: nil, required: false, nullable: false, emit_null: false)]
    getter _type : Twilio::AccountEnumType? = nil

    # The URI for this resource, relative to `https://api.twilio.com`
    @[JSON::Field(key: "uri", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: uri.nil? && !uri_present?)]
    getter uri : String? = nil

    @[JSON::Field(ignore: true)]
    property? uri_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @auth_token : String? = nil,
      @date_created : Time? = nil,
      @date_updated : Time? = nil,
      @friendly_name : String? = nil,
      @owner_account_sid : String? = nil,
      @sid : String? = nil,
      @status : Twilio::AccountEnumStatus? = nil,
      @subresource_uris : Hash(String, String)? = nil,
      @_type : Twilio::AccountEnumType? = nil,
      @uri : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_owner_account_sid = @owner_account_sid).nil?
        if max_length_error = OpenApi::PrimitiveValidator.max_length_error("owner_account_sid", _owner_account_sid.to_s.size, MAX_LENGTH_FOR_OWNER_ACCOUNT_SID)
          invalid_properties.push(max_length_error)
        end

        if min_length_error = OpenApi::PrimitiveValidator.min_length_error("owner_account_sid", _owner_account_sid.to_s.size, MIN_LENGTH_FOR_OWNER_ACCOUNT_SID)
          invalid_properties.push(min_length_error)
        end

        if pattern_error = OpenApi::PrimitiveValidator.pattern_error("owner_account_sid", _owner_account_sid, PATTERN_FOR_OWNER_ACCOUNT_SID)
          invalid_properties.push(pattern_error)
        end
      end
      unless (_sid = @sid).nil?
        if max_length_error = OpenApi::PrimitiveValidator.max_length_error("sid", _sid.to_s.size, MAX_LENGTH_FOR_SID)
          invalid_properties.push(max_length_error)
        end

        if min_length_error = OpenApi::PrimitiveValidator.min_length_error("sid", _sid.to_s.size, MIN_LENGTH_FOR_SID)
          invalid_properties.push(min_length_error)
        end

        if pattern_error = OpenApi::PrimitiveValidator.pattern_error("sid", _sid, PATTERN_FOR_SID)
          invalid_properties.push(pattern_error)
        end
      end
      unless (_status = @status).nil?
        invalid_properties.push(_status.error_message) if !_status.valid?
      end

      unless (__type = @_type).nil?
        invalid_properties.push(__type.error_message) if !__type.valid?
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      unless (_owner_account_sid = @owner_account_sid).nil?
        return false if _owner_account_sid.to_s.size > MAX_LENGTH_FOR_OWNER_ACCOUNT_SID
        return false if _owner_account_sid.to_s.size < MIN_LENGTH_FOR_OWNER_ACCOUNT_SID
        return false if !PATTERN_FOR_OWNER_ACCOUNT_SID.matches?(_owner_account_sid)
      end

      unless (_sid = @sid).nil?
        return false if _sid.to_s.size > MAX_LENGTH_FOR_SID
        return false if _sid.to_s.size < MIN_LENGTH_FOR_SID
        return false if !PATTERN_FOR_SID.matches?(_sid)
      end

      unless (_status = @status).nil?
        return false if !_status.valid?
      end

      unless (__type = @_type).nil?
        return false if !__type.valid?
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] auth_token Object to be assigned
    def auth_token=(new_value : String?)
      @auth_token = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] date_created Object to be assigned
    def date_created=(new_value : Time?)
      @date_created = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] date_updated Object to be assigned
    def date_updated=(new_value : Time?)
      @date_updated = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] friendly_name Object to be assigned
    def friendly_name=(new_value : String?)
      @friendly_name = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] owner_account_sid Object to be assigned
    def owner_account_sid=(new_value : String?)
      unless new_value.nil?
        OpenApi::PrimitiveValidator.validate_max_length("owner_account_sid", new_value.to_s.size, MAX_LENGTH_FOR_OWNER_ACCOUNT_SID)
        OpenApi::PrimitiveValidator.validate_min_length("owner_account_sid", new_value.to_s.size, MIN_LENGTH_FOR_OWNER_ACCOUNT_SID)
        OpenApi::PrimitiveValidator.validate_pattern("owner_account_sid", new_value, PATTERN_FOR_OWNER_ACCOUNT_SID)
      end

      @owner_account_sid = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sid Object to be assigned
    def sid=(new_value : String?)
      unless new_value.nil?
        OpenApi::PrimitiveValidator.validate_max_length("sid", new_value.to_s.size, MAX_LENGTH_FOR_SID)
        OpenApi::PrimitiveValidator.validate_min_length("sid", new_value.to_s.size, MIN_LENGTH_FOR_SID)
        OpenApi::PrimitiveValidator.validate_pattern("sid", new_value, PATTERN_FOR_SID)
      end

      @sid = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(new_value : Twilio::AccountEnumStatus?)
      unless new_value.nil?
        new_value.validate
      end

      @status = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] subresource_uris Object to be assigned
    def subresource_uris=(new_value : Hash(String, String)?)
      @subresource_uris = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] _type Object to be assigned
    def _type=(new_value : Twilio::AccountEnumType?)
      unless new_value.nil?
        new_value.validate
      end

      @_type = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] uri Object to be assigned
    def uri=(new_value : String?)
      @uri = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@auth_token, @auth_token_present, @date_created, @date_created_present, @date_updated, @date_updated_present, @friendly_name, @friendly_name_present, @owner_account_sid, @owner_account_sid_present, @sid, @sid_present, @status, @subresource_uris, @subresource_uris_present, @_type, @uri, @uri_present)
  end
end
