#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "../../core"

require "./http_method"

module Twilio
  class Application
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Optional Properties

    # The SID of the Account that created the resource
    @[JSON::Field(key: "account_sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: account_sid.nil? && !account_sid_present?)]
    getter account_sid : String? = nil
    MAX_LENGTH_FOR_ACCOUNT_SID = 34
    MIN_LENGTH_FOR_ACCOUNT_SID = 34
    PATTERN_FOR_ACCOUNT_SID    = /^AC[0-9a-fA-F]{32}$/

    @[JSON::Field(ignore: true)]
    property? account_sid_present : Bool = false

    # The API version used to start a new TwiML session
    @[JSON::Field(key: "api_version", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: api_version.nil? && !api_version_present?)]
    getter api_version : String? = nil

    @[JSON::Field(ignore: true)]
    property? api_version_present : Bool = false

    # The RFC 2822 date and time in GMT that the resource was created
    @[JSON::Field(key: "date_created", type: Time?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: date_created.nil? && !date_created_present?, converter: Time::RFC2822Converter)]
    getter date_created : Time? = nil

    @[JSON::Field(ignore: true)]
    property? date_created_present : Bool = false

    # The RFC 2822 date and time in GMT that the resource was last updated
    @[JSON::Field(key: "date_updated", type: Time?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: date_updated.nil? && !date_updated_present?, converter: Time::RFC2822Converter)]
    getter date_updated : Time? = nil

    @[JSON::Field(ignore: true)]
    property? date_updated_present : Bool = false

    # The string that you assigned to describe the resource
    @[JSON::Field(key: "friendly_name", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: friendly_name.nil? && !friendly_name_present?)]
    getter friendly_name : String? = nil

    @[JSON::Field(ignore: true)]
    property? friendly_name_present : Bool = false

    # The URL to send message status information to your application
    @[JSON::Field(key: "message_status_callback", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: message_status_callback.nil? && !message_status_callback_present?)]
    getter message_status_callback : String? = nil

    @[JSON::Field(ignore: true)]
    property? message_status_callback_present : Bool = false

    # The unique string that identifies the resource
    @[JSON::Field(key: "sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: sid.nil? && !sid_present?)]
    getter sid : String? = nil
    MAX_LENGTH_FOR_SID = 34
    MIN_LENGTH_FOR_SID = 34
    PATTERN_FOR_SID    = /^AP[0-9a-fA-F]{32}$/

    @[JSON::Field(ignore: true)]
    property? sid_present : Bool = false

    @[JSON::Field(key: "sms_fallback_method", type: Twilio::HttpMethod?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: sms_fallback_method.nil? && !sms_fallback_method_present?)]
    getter sms_fallback_method : Twilio::HttpMethod? = nil

    @[JSON::Field(ignore: true)]
    property? sms_fallback_method_present : Bool = false

    # The URL that we call when an error occurs while retrieving or executing the TwiML
    @[JSON::Field(key: "sms_fallback_url", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: sms_fallback_url.nil? && !sms_fallback_url_present?)]
    getter sms_fallback_url : String? = nil

    @[JSON::Field(ignore: true)]
    property? sms_fallback_url_present : Bool = false

    @[JSON::Field(key: "sms_method", type: Twilio::HttpMethod?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: sms_method.nil? && !sms_method_present?)]
    getter sms_method : Twilio::HttpMethod? = nil

    @[JSON::Field(ignore: true)]
    property? sms_method_present : Bool = false

    # The URL to send status information to your application
    @[JSON::Field(key: "sms_status_callback", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: sms_status_callback.nil? && !sms_status_callback_present?)]
    getter sms_status_callback : String? = nil

    @[JSON::Field(ignore: true)]
    property? sms_status_callback_present : Bool = false

    # The URL we call when the phone number receives an incoming SMS message
    @[JSON::Field(key: "sms_url", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: sms_url.nil? && !sms_url_present?)]
    getter sms_url : String? = nil

    @[JSON::Field(ignore: true)]
    property? sms_url_present : Bool = false

    # The URL to send status information to your application
    @[JSON::Field(key: "status_callback", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: status_callback.nil? && !status_callback_present?)]
    getter status_callback : String? = nil

    @[JSON::Field(ignore: true)]
    property? status_callback_present : Bool = false

    @[JSON::Field(key: "status_callback_method", type: Twilio::HttpMethod?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: status_callback_method.nil? && !status_callback_method_present?)]
    getter status_callback_method : Twilio::HttpMethod? = nil

    @[JSON::Field(ignore: true)]
    property? status_callback_method_present : Bool = false

    # The URI of the resource, relative to `https://api.twilio.com`
    @[JSON::Field(key: "uri", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: uri.nil? && !uri_present?)]
    getter uri : String? = nil

    @[JSON::Field(ignore: true)]
    property? uri_present : Bool = false

    # Whether to lookup the caller's name
    @[JSON::Field(key: "voice_caller_id_lookup", type: Bool?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: voice_caller_id_lookup.nil? && !voice_caller_id_lookup_present?)]
    getter voice_caller_id_lookup : Bool? = nil

    @[JSON::Field(ignore: true)]
    property? voice_caller_id_lookup_present : Bool = false

    @[JSON::Field(key: "voice_fallback_method", type: Twilio::HttpMethod?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: voice_fallback_method.nil? && !voice_fallback_method_present?)]
    getter voice_fallback_method : Twilio::HttpMethod? = nil

    @[JSON::Field(ignore: true)]
    property? voice_fallback_method_present : Bool = false

    # The URL we call when a TwiML error occurs
    @[JSON::Field(key: "voice_fallback_url", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: voice_fallback_url.nil? && !voice_fallback_url_present?)]
    getter voice_fallback_url : String? = nil

    @[JSON::Field(ignore: true)]
    property? voice_fallback_url_present : Bool = false

    @[JSON::Field(key: "voice_method", type: Twilio::HttpMethod?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: voice_method.nil? && !voice_method_present?)]
    getter voice_method : Twilio::HttpMethod? = nil

    @[JSON::Field(ignore: true)]
    property? voice_method_present : Bool = false

    # The URL we call when the phone number receives a call
    @[JSON::Field(key: "voice_url", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: voice_url.nil? && !voice_url_present?)]
    getter voice_url : String? = nil

    @[JSON::Field(ignore: true)]
    property? voice_url_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @account_sid : String? = nil,
      @api_version : String? = nil,
      @date_created : Time? = nil,
      @date_updated : Time? = nil,
      @friendly_name : String? = nil,
      @message_status_callback : String? = nil,
      @sid : String? = nil,
      @sms_fallback_method : Twilio::HttpMethod? = nil,
      @sms_fallback_url : String? = nil,
      @sms_method : Twilio::HttpMethod? = nil,
      @sms_status_callback : String? = nil,
      @sms_url : String? = nil,
      @status_callback : String? = nil,
      @status_callback_method : Twilio::HttpMethod? = nil,
      @uri : String? = nil,
      @voice_caller_id_lookup : Bool? = nil,
      @voice_fallback_method : Twilio::HttpMethod? = nil,
      @voice_fallback_url : String? = nil,
      @voice_method : Twilio::HttpMethod? = nil,
      @voice_url : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_account_sid = @account_sid).nil?
        if max_length_error = OpenApi::PrimitiveValidator.max_length_error("account_sid", _account_sid.to_s.size, MAX_LENGTH_FOR_ACCOUNT_SID)
          invalid_properties.push(max_length_error)
        end

        if min_length_error = OpenApi::PrimitiveValidator.min_length_error("account_sid", _account_sid.to_s.size, MIN_LENGTH_FOR_ACCOUNT_SID)
          invalid_properties.push(min_length_error)
        end

        if pattern_error = OpenApi::PrimitiveValidator.pattern_error("account_sid", _account_sid, PATTERN_FOR_ACCOUNT_SID)
          invalid_properties.push(pattern_error)
        end
      end

      unless (_sid = @sid).nil?
        if max_length_error = OpenApi::PrimitiveValidator.max_length_error("sid", _sid.to_s.size, MAX_LENGTH_FOR_SID)
          invalid_properties.push(max_length_error)
        end

        if min_length_error = OpenApi::PrimitiveValidator.min_length_error("sid", _sid.to_s.size, MIN_LENGTH_FOR_SID)
          invalid_properties.push(min_length_error)
        end

        if pattern_error = OpenApi::PrimitiveValidator.pattern_error("sid", _sid, PATTERN_FOR_SID)
          invalid_properties.push(pattern_error)
        end
      end
      unless (_sms_fallback_method = @sms_fallback_method).nil?
        invalid_properties.push(_sms_fallback_method.error_message) if !_sms_fallback_method.valid?
      end

      unless (_sms_method = @sms_method).nil?
        invalid_properties.push(_sms_method.error_message) if !_sms_method.valid?
      end

      unless (_status_callback_method = @status_callback_method).nil?
        invalid_properties.push(_status_callback_method.error_message) if !_status_callback_method.valid?
      end

      unless (_voice_fallback_method = @voice_fallback_method).nil?
        invalid_properties.push(_voice_fallback_method.error_message) if !_voice_fallback_method.valid?
      end

      unless (_voice_method = @voice_method).nil?
        invalid_properties.push(_voice_method.error_message) if !_voice_method.valid?
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      unless (_account_sid = @account_sid).nil?
        return false if _account_sid.to_s.size > MAX_LENGTH_FOR_ACCOUNT_SID
        return false if _account_sid.to_s.size < MIN_LENGTH_FOR_ACCOUNT_SID
        return false if !PATTERN_FOR_ACCOUNT_SID.matches?(_account_sid)
      end

      unless (_sid = @sid).nil?
        return false if _sid.to_s.size > MAX_LENGTH_FOR_SID
        return false if _sid.to_s.size < MIN_LENGTH_FOR_SID
        return false if !PATTERN_FOR_SID.matches?(_sid)
      end

      unless (_sms_fallback_method = @sms_fallback_method).nil?
        return false if !_sms_fallback_method.valid?
      end

      unless (_sms_method = @sms_method).nil?
        return false if !_sms_method.valid?
      end

      unless (_status_callback_method = @status_callback_method).nil?
        return false if !_status_callback_method.valid?
      end

      unless (_voice_fallback_method = @voice_fallback_method).nil?
        return false if !_voice_fallback_method.valid?
      end

      unless (_voice_method = @voice_method).nil?
        return false if !_voice_method.valid?
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] account_sid Object to be assigned
    def account_sid=(new_value : String?)
      unless new_value.nil?
        OpenApi::PrimitiveValidator.validate_max_length("account_sid", new_value.to_s.size, MAX_LENGTH_FOR_ACCOUNT_SID)
        OpenApi::PrimitiveValidator.validate_min_length("account_sid", new_value.to_s.size, MIN_LENGTH_FOR_ACCOUNT_SID)
        OpenApi::PrimitiveValidator.validate_pattern("account_sid", new_value, PATTERN_FOR_ACCOUNT_SID)
      end

      @account_sid = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] api_version Object to be assigned
    def api_version=(new_value : String?)
      @api_version = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] date_created Object to be assigned
    def date_created=(new_value : Time?)
      @date_created = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] date_updated Object to be assigned
    def date_updated=(new_value : Time?)
      @date_updated = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] friendly_name Object to be assigned
    def friendly_name=(new_value : String?)
      @friendly_name = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] message_status_callback Object to be assigned
    def message_status_callback=(new_value : String?)
      @message_status_callback = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sid Object to be assigned
    def sid=(new_value : String?)
      unless new_value.nil?
        OpenApi::PrimitiveValidator.validate_max_length("sid", new_value.to_s.size, MAX_LENGTH_FOR_SID)
        OpenApi::PrimitiveValidator.validate_min_length("sid", new_value.to_s.size, MIN_LENGTH_FOR_SID)
        OpenApi::PrimitiveValidator.validate_pattern("sid", new_value, PATTERN_FOR_SID)
      end

      @sid = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sms_fallback_method Object to be assigned
    def sms_fallback_method=(new_value : Twilio::HttpMethod?)
      unless new_value.nil?
        new_value.validate
      end

      @sms_fallback_method = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sms_fallback_url Object to be assigned
    def sms_fallback_url=(new_value : String?)
      @sms_fallback_url = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sms_method Object to be assigned
    def sms_method=(new_value : Twilio::HttpMethod?)
      unless new_value.nil?
        new_value.validate
      end

      @sms_method = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sms_status_callback Object to be assigned
    def sms_status_callback=(new_value : String?)
      @sms_status_callback = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sms_url Object to be assigned
    def sms_url=(new_value : String?)
      @sms_url = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status_callback Object to be assigned
    def status_callback=(new_value : String?)
      @status_callback = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status_callback_method Object to be assigned
    def status_callback_method=(new_value : Twilio::HttpMethod?)
      unless new_value.nil?
        new_value.validate
      end

      @status_callback_method = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] uri Object to be assigned
    def uri=(new_value : String?)
      @uri = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] voice_caller_id_lookup Object to be assigned
    def voice_caller_id_lookup=(new_value : Bool?)
      @voice_caller_id_lookup = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] voice_fallback_method Object to be assigned
    def voice_fallback_method=(new_value : Twilio::HttpMethod?)
      unless new_value.nil?
        new_value.validate
      end

      @voice_fallback_method = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] voice_fallback_url Object to be assigned
    def voice_fallback_url=(new_value : String?)
      @voice_fallback_url = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] voice_method Object to be assigned
    def voice_method=(new_value : Twilio::HttpMethod?)
      unless new_value.nil?
        new_value.validate
      end

      @voice_method = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] voice_url Object to be assigned
    def voice_url=(new_value : String?)
      @voice_url = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@account_sid, @account_sid_present, @api_version, @api_version_present, @date_created, @date_created_present, @date_updated, @date_updated_present, @friendly_name, @friendly_name_present, @message_status_callback, @message_status_callback_present, @sid, @sid_present, @sms_fallback_method, @sms_fallback_method_present, @sms_fallback_url, @sms_fallback_url_present, @sms_method, @sms_method_present, @sms_status_callback, @sms_status_callback_present, @sms_url, @sms_url_present, @status_callback, @status_callback_present, @status_callback_method, @status_callback_method_present, @uri, @uri_present, @voice_caller_id_lookup, @voice_caller_id_lookup_present, @voice_fallback_method, @voice_fallback_method_present, @voice_fallback_url, @voice_fallback_url_present, @voice_method, @voice_method_present, @voice_url, @voice_url_present)
  end
end
