#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.29.1
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module Twilio
  class CallCallNotificationInstance
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Json

    # Optional properties

    # The SID of the Account that created the resource
    @[JSON::Field(key: "account_sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: account_sid.nil? && !account_sid_present?)]
    getter account_sid : String? = nil

    @[JSON::Field(ignore: true)]
    property? account_sid_present : Bool = false

    # The API version used to create the Call Notification resource
    @[JSON::Field(key: "api_version", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: api_version.nil? && !api_version_present?)]
    getter api_version : String? = nil

    @[JSON::Field(ignore: true)]
    property? api_version_present : Bool = false

    # The SID of the Call the resource is associated with
    @[JSON::Field(key: "call_sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: call_sid.nil? && !call_sid_present?)]
    getter call_sid : String? = nil

    @[JSON::Field(ignore: true)]
    property? call_sid_present : Bool = false

    # The RFC 2822 date and time in GMT that the resource was created
    @[JSON::Field(key: "date_created", type: Time?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: date_created.nil? && !date_created_present?, converter: Time::RFC2822Converter)]
    getter date_created : Time? = nil

    @[JSON::Field(ignore: true)]
    property? date_created_present : Bool = false

    # The RFC 2822 date and time in GMT that the resource was last updated
    @[JSON::Field(key: "date_updated", type: Time?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: date_updated.nil? && !date_updated_present?, converter: Time::RFC2822Converter)]
    getter date_updated : Time? = nil

    @[JSON::Field(ignore: true)]
    property? date_updated_present : Bool = false

    # A unique error code corresponding to the notification
    @[JSON::Field(key: "error_code", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: error_code.nil? && !error_code_present?)]
    getter error_code : String? = nil

    @[JSON::Field(ignore: true)]
    property? error_code_present : Bool = false

    # An integer log level
    @[JSON::Field(key: "log", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: log.nil? && !log_present?)]
    getter log : String? = nil

    @[JSON::Field(ignore: true)]
    property? log_present : Bool = false

    # The date the notification was generated
    @[JSON::Field(key: "message_date", type: Time?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: message_date.nil? && !message_date_present?, converter: Time::RFC2822Converter)]
    getter message_date : Time? = nil

    @[JSON::Field(ignore: true)]
    property? message_date_present : Bool = false

    # The text of the notification
    @[JSON::Field(key: "message_text", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: message_text.nil? && !message_text_present?)]
    getter message_text : String? = nil

    @[JSON::Field(ignore: true)]
    property? message_text_present : Bool = false

    # A URL for more information about the error code
    @[JSON::Field(key: "more_info", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: more_info.nil? && !more_info_present?)]
    getter more_info : String? = nil

    @[JSON::Field(ignore: true)]
    property? more_info_present : Bool = false

    # HTTP method used with the request url
    @[JSON::Field(key: "request_method", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: request_method.nil? && !request_method_present?)]
    getter request_method : String? = nil

    @[JSON::Field(ignore: true)]
    property? request_method_present : Bool = false

    ENUM_VALIDATOR_FOR_REQUEST_METHOD = EnumValidator.new("request_method", "String", ["HEAD", "GET", "POST", "PATCH", "PUT", "DELETE"])

    # URL of the resource that generated the notification
    @[JSON::Field(key: "request_url", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: request_url.nil? && !request_url_present?)]
    getter request_url : String? = nil

    @[JSON::Field(ignore: true)]
    property? request_url_present : Bool = false

    # Twilio-generated HTTP variables sent to the server
    @[JSON::Field(key: "request_variables", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: request_variables.nil? && !request_variables_present?)]
    getter request_variables : String? = nil

    @[JSON::Field(ignore: true)]
    property? request_variables_present : Bool = false

    # The HTTP body returned by your server
    @[JSON::Field(key: "response_body", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: response_body.nil? && !response_body_present?)]
    getter response_body : String? = nil

    @[JSON::Field(ignore: true)]
    property? response_body_present : Bool = false

    # The HTTP headers returned by your server
    @[JSON::Field(key: "response_headers", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: response_headers.nil? && !response_headers_present?)]
    getter response_headers : String? = nil

    @[JSON::Field(ignore: true)]
    property? response_headers_present : Bool = false

    # The unique string that identifies the resource
    @[JSON::Field(key: "sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: sid.nil? && !sid_present?)]
    getter sid : String? = nil

    @[JSON::Field(ignore: true)]
    property? sid_present : Bool = false

    # The URI of the resource, relative to `https://api.twilio.com`
    @[JSON::Field(key: "uri", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: uri.nil? && !uri_present?)]
    getter uri : String? = nil

    @[JSON::Field(ignore: true)]
    property? uri_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @account_sid : String? = nil,
      @api_version : String? = nil,
      @call_sid : String? = nil,
      @date_created : Time? = nil,
      @date_updated : Time? = nil,
      @error_code : String? = nil,
      @log : String? = nil,
      @message_date : Time? = nil,
      @message_text : String? = nil,
      @more_info : String? = nil,
      @request_method : String? = nil,
      @request_url : String? = nil,
      @request_variables : String? = nil,
      @response_body : String? = nil,
      @response_headers : String? = nil,
      @sid : String? = nil,
      @uri : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if _account_sid = @account_sid
        if _account_sid.to_s.size > 34
          invalid_properties.push("invalid value for \"account_sid\", the character length must be smaller than or equal to 34.")
        end

        if _account_sid.to_s.size < 34
          invalid_properties.push("invalid value for \"account_sid\", the character length must be great than or equal to 34.")
        end

        pattern = /^AC[0-9a-fA-F]{32}$/
        if _account_sid !~ pattern
          invalid_properties.push("invalid value for \"account_sid\", must conform to the pattern #{pattern}.")
        end
      end
      if _call_sid = @call_sid
        if _call_sid.to_s.size > 34
          invalid_properties.push("invalid value for \"call_sid\", the character length must be smaller than or equal to 34.")
        end

        if _call_sid.to_s.size < 34
          invalid_properties.push("invalid value for \"call_sid\", the character length must be great than or equal to 34.")
        end

        pattern = /^CA[0-9a-fA-F]{32}$/
        if _call_sid !~ pattern
          invalid_properties.push("invalid value for \"call_sid\", must conform to the pattern #{pattern}.")
        end
      end

      invalid_properties.push(ENUM_VALIDATOR_FOR_REQUEST_METHOD.error_message) unless ENUM_VALIDATOR_FOR_REQUEST_METHOD.valid?(@request_method)
      if _sid = @sid
        if _sid.to_s.size > 34
          invalid_properties.push("invalid value for \"sid\", the character length must be smaller than or equal to 34.")
        end

        if _sid.to_s.size < 34
          invalid_properties.push("invalid value for \"sid\", the character length must be great than or equal to 34.")
        end

        pattern = /^NO[0-9a-fA-F]{32}$/
        if _sid !~ pattern
          invalid_properties.push("invalid value for \"sid\", must conform to the pattern #{pattern}.")
        end
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      if _account_sid = @account_sid
        return false if _account_sid.to_s.size > 34
        return false if _account_sid.to_s.size < 34
        return false if _account_sid !~ /^AC[0-9a-fA-F]{32}$/
      end
      if _call_sid = @call_sid
        return false if _call_sid.to_s.size > 34
        return false if _call_sid.to_s.size < 34
        return false if _call_sid !~ /^CA[0-9a-fA-F]{32}$/
      end
      return false unless ENUM_VALIDATOR_FOR_REQUEST_METHOD.valid?(@request_method)
      if _sid = @sid
        return false if _sid.to_s.size > 34
        return false if _sid.to_s.size < 34
        return false if _sid !~ /^NO[0-9a-fA-F]{32}$/
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] account_sid Object to be assigned
    def account_sid=(account_sid : String?)
      if account_sid.nil?
        return @account_sid = nil
      end
      _account_sid = account_sid.not_nil!
      if _account_sid.to_s.size > 34
        raise ArgumentError.new("invalid value for \"account_sid\", the character length must be smaller than or equal to 34.")
      end

      if _account_sid.to_s.size < 34
        raise ArgumentError.new("invalid value for \"account_sid\", the character length must be great than or equal to 34.")
      end

      pattern = /^AC[0-9a-fA-F]{32}$/
      if _account_sid !~ pattern
        raise ArgumentError.new("invalid value for \"account_sid\", must conform to the pattern #{pattern}.")
      end

      @account_sid = account_sid
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] api_version Object to be assigned
    def api_version=(api_version : String?)
      if api_version.nil?
        return @api_version = nil
      end
      @api_version = api_version
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] call_sid Object to be assigned
    def call_sid=(call_sid : String?)
      if call_sid.nil?
        return @call_sid = nil
      end
      _call_sid = call_sid.not_nil!
      if _call_sid.to_s.size > 34
        raise ArgumentError.new("invalid value for \"call_sid\", the character length must be smaller than or equal to 34.")
      end

      if _call_sid.to_s.size < 34
        raise ArgumentError.new("invalid value for \"call_sid\", the character length must be great than or equal to 34.")
      end

      pattern = /^CA[0-9a-fA-F]{32}$/
      if _call_sid !~ pattern
        raise ArgumentError.new("invalid value for \"call_sid\", must conform to the pattern #{pattern}.")
      end

      @call_sid = call_sid
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] date_created Object to be assigned
    def date_created=(date_created : Time?)
      if date_created.nil?
        return @date_created = nil
      end
      @date_created = date_created
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] date_updated Object to be assigned
    def date_updated=(date_updated : Time?)
      if date_updated.nil?
        return @date_updated = nil
      end
      @date_updated = date_updated
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] error_code Object to be assigned
    def error_code=(error_code : String?)
      if error_code.nil?
        return @error_code = nil
      end
      @error_code = error_code
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] log Object to be assigned
    def log=(log : String?)
      if log.nil?
        return @log = nil
      end
      @log = log
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] message_date Object to be assigned
    def message_date=(message_date : Time?)
      if message_date.nil?
        return @message_date = nil
      end
      @message_date = message_date
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] message_text Object to be assigned
    def message_text=(message_text : String?)
      if message_text.nil?
        return @message_text = nil
      end
      @message_text = message_text
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] more_info Object to be assigned
    def more_info=(more_info : String?)
      if more_info.nil?
        return @more_info = nil
      end
      @more_info = more_info
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] request_method Object to be assigned
    def request_method=(request_method : String?)
      if request_method.nil?
        return @request_method = nil
      end
      _request_method = request_method.not_nil!
      ENUM_VALIDATOR_FOR_REQUEST_METHOD.valid!(_request_method)
      @request_method = request_method
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] request_url Object to be assigned
    def request_url=(request_url : String?)
      if request_url.nil?
        return @request_url = nil
      end
      @request_url = request_url
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] request_variables Object to be assigned
    def request_variables=(request_variables : String?)
      if request_variables.nil?
        return @request_variables = nil
      end
      @request_variables = request_variables
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] response_body Object to be assigned
    def response_body=(response_body : String?)
      if response_body.nil?
        return @response_body = nil
      end
      @response_body = response_body
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] response_headers Object to be assigned
    def response_headers=(response_headers : String?)
      if response_headers.nil?
        return @response_headers = nil
      end
      @response_headers = response_headers
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sid Object to be assigned
    def sid=(sid : String?)
      if sid.nil?
        return @sid = nil
      end
      _sid = sid.not_nil!
      if _sid.to_s.size > 34
        raise ArgumentError.new("invalid value for \"sid\", the character length must be smaller than or equal to 34.")
      end

      if _sid.to_s.size < 34
        raise ArgumentError.new("invalid value for \"sid\", the character length must be great than or equal to 34.")
      end

      pattern = /^NO[0-9a-fA-F]{32}$/
      if _sid !~ pattern
        raise ArgumentError.new("invalid value for \"sid\", must conform to the pattern #{pattern}.")
      end

      @sid = sid
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] uri Object to be assigned
    def uri=(uri : String?)
      if uri.nil?
        return @uri = nil
      end
      @uri = uri
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@account_sid, @account_sid_present, @api_version, @api_version_present, @call_sid, @call_sid_present, @date_created, @date_created_present, @date_updated, @date_updated_present, @error_code, @error_code_present, @log, @log_present, @message_date, @message_date_present, @message_text, @message_text_present, @more_info, @more_info_present, @request_method, @request_method_present, @request_url, @request_url_present, @request_variables, @request_variables_present, @response_body, @response_body_present, @response_headers, @response_headers_present, @sid, @sid_present, @uri, @uri_present)
  end
end
