#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.38.0
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module Twilio
  class IncomingPhoneNumberIncomingPhoneNumberAssignedAddOnIncomingPhoneNumberAssignedAddOnExtension
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Optional Properties

    # The SID of the Account that created the resource
    @[JSON::Field(key: "account_sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: account_sid.nil? && !account_sid_present?)]
    getter account_sid : String? = nil
    MAX_LENGTH_FOR_ACCOUNT_SID = 34
    MIN_LENGTH_FOR_ACCOUNT_SID = 34
    PATTERN_FOR_ACCOUNT_SID    = /^AC[0-9a-fA-F]{32}$/

    @[JSON::Field(ignore: true)]
    property? account_sid_present : Bool = false

    # The SID that uniquely identifies the assigned Add-on installation
    @[JSON::Field(key: "assigned_add_on_sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: assigned_add_on_sid.nil? && !assigned_add_on_sid_present?)]
    getter assigned_add_on_sid : String? = nil
    MAX_LENGTH_FOR_ASSIGNED_ADD_ON_SID = 34
    MIN_LENGTH_FOR_ASSIGNED_ADD_ON_SID = 34
    PATTERN_FOR_ASSIGNED_ADD_ON_SID    = /^XE[0-9a-fA-F]{32}$/

    @[JSON::Field(ignore: true)]
    property? assigned_add_on_sid_present : Bool = false

    # Whether the Extension will be invoked
    @[JSON::Field(key: "enabled", type: Bool?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: enabled.nil? && !enabled_present?)]
    getter enabled : Bool? = nil

    @[JSON::Field(ignore: true)]
    property? enabled_present : Bool = false

    # The string that you assigned to describe the resource
    @[JSON::Field(key: "friendly_name", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: friendly_name.nil? && !friendly_name_present?)]
    getter friendly_name : String? = nil

    @[JSON::Field(ignore: true)]
    property? friendly_name_present : Bool = false

    # A string that you assigned to describe the Product this Extension is used within
    @[JSON::Field(key: "product_name", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: product_name.nil? && !product_name_present?)]
    getter product_name : String? = nil

    @[JSON::Field(ignore: true)]
    property? product_name_present : Bool = false

    # The SID of the Phone Number to which the Add-on is assigned
    @[JSON::Field(key: "resource_sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: resource_sid.nil? && !resource_sid_present?)]
    getter resource_sid : String? = nil
    MAX_LENGTH_FOR_RESOURCE_SID = 34
    MIN_LENGTH_FOR_RESOURCE_SID = 34
    PATTERN_FOR_RESOURCE_SID    = /^PN[0-9a-fA-F]{32}$/

    @[JSON::Field(ignore: true)]
    property? resource_sid_present : Bool = false

    # The unique string that identifies the resource
    @[JSON::Field(key: "sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: sid.nil? && !sid_present?)]
    getter sid : String? = nil
    MAX_LENGTH_FOR_SID = 34
    MIN_LENGTH_FOR_SID = 34
    PATTERN_FOR_SID    = /^XF[0-9a-fA-F]{32}$/

    @[JSON::Field(ignore: true)]
    property? sid_present : Bool = false

    # An application-defined string that uniquely identifies the resource
    @[JSON::Field(key: "unique_name", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: unique_name.nil? && !unique_name_present?)]
    getter unique_name : String? = nil

    @[JSON::Field(ignore: true)]
    property? unique_name_present : Bool = false

    # The URI of the resource, relative to `https://api.twilio.com`
    @[JSON::Field(key: "uri", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: uri.nil? && !uri_present?)]
    getter uri : String? = nil

    @[JSON::Field(ignore: true)]
    property? uri_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @account_sid : String? = nil,
      @assigned_add_on_sid : String? = nil,
      @enabled : Bool? = nil,
      @friendly_name : String? = nil,
      @product_name : String? = nil,
      @resource_sid : String? = nil,
      @sid : String? = nil,
      @unique_name : String? = nil,
      @uri : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_account_sid = @account_sid).nil?
        if max_length_error = OpenApi::PrimitiveValidator.max_length_error("account_sid", _account_sid.to_s.size, MAX_LENGTH_FOR_ACCOUNT_SID)
          invalid_properties.push(max_length_error)
        end

        if min_length_error = OpenApi::PrimitiveValidator.min_length_error("account_sid", _account_sid.to_s.size, MIN_LENGTH_FOR_ACCOUNT_SID)
          invalid_properties.push(min_length_error)
        end

        if pattern_error = OpenApi::PrimitiveValidator.pattern_error("account_sid", _account_sid, PATTERN_FOR_ACCOUNT_SID)
          invalid_properties.push(pattern_error)
        end
      end
      unless (_assigned_add_on_sid = @assigned_add_on_sid).nil?
        if max_length_error = OpenApi::PrimitiveValidator.max_length_error("assigned_add_on_sid", _assigned_add_on_sid.to_s.size, MAX_LENGTH_FOR_ASSIGNED_ADD_ON_SID)
          invalid_properties.push(max_length_error)
        end

        if min_length_error = OpenApi::PrimitiveValidator.min_length_error("assigned_add_on_sid", _assigned_add_on_sid.to_s.size, MIN_LENGTH_FOR_ASSIGNED_ADD_ON_SID)
          invalid_properties.push(min_length_error)
        end

        if pattern_error = OpenApi::PrimitiveValidator.pattern_error("assigned_add_on_sid", _assigned_add_on_sid, PATTERN_FOR_ASSIGNED_ADD_ON_SID)
          invalid_properties.push(pattern_error)
        end
      end

      unless (_resource_sid = @resource_sid).nil?
        if max_length_error = OpenApi::PrimitiveValidator.max_length_error("resource_sid", _resource_sid.to_s.size, MAX_LENGTH_FOR_RESOURCE_SID)
          invalid_properties.push(max_length_error)
        end

        if min_length_error = OpenApi::PrimitiveValidator.min_length_error("resource_sid", _resource_sid.to_s.size, MIN_LENGTH_FOR_RESOURCE_SID)
          invalid_properties.push(min_length_error)
        end

        if pattern_error = OpenApi::PrimitiveValidator.pattern_error("resource_sid", _resource_sid, PATTERN_FOR_RESOURCE_SID)
          invalid_properties.push(pattern_error)
        end
      end
      unless (_sid = @sid).nil?
        if max_length_error = OpenApi::PrimitiveValidator.max_length_error("sid", _sid.to_s.size, MAX_LENGTH_FOR_SID)
          invalid_properties.push(max_length_error)
        end

        if min_length_error = OpenApi::PrimitiveValidator.min_length_error("sid", _sid.to_s.size, MIN_LENGTH_FOR_SID)
          invalid_properties.push(min_length_error)
        end

        if pattern_error = OpenApi::PrimitiveValidator.pattern_error("sid", _sid, PATTERN_FOR_SID)
          invalid_properties.push(pattern_error)
        end
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      unless (_account_sid = @account_sid).nil?
        return false if _account_sid.to_s.size > MAX_LENGTH_FOR_ACCOUNT_SID
        return false if _account_sid.to_s.size < MIN_LENGTH_FOR_ACCOUNT_SID
        return false if !PATTERN_FOR_ACCOUNT_SID.matches?(_account_sid)
      end

      unless (_assigned_add_on_sid = @assigned_add_on_sid).nil?
        return false if _assigned_add_on_sid.to_s.size > MAX_LENGTH_FOR_ASSIGNED_ADD_ON_SID
        return false if _assigned_add_on_sid.to_s.size < MIN_LENGTH_FOR_ASSIGNED_ADD_ON_SID
        return false if !PATTERN_FOR_ASSIGNED_ADD_ON_SID.matches?(_assigned_add_on_sid)
      end

      unless (_resource_sid = @resource_sid).nil?
        return false if _resource_sid.to_s.size > MAX_LENGTH_FOR_RESOURCE_SID
        return false if _resource_sid.to_s.size < MIN_LENGTH_FOR_RESOURCE_SID
        return false if !PATTERN_FOR_RESOURCE_SID.matches?(_resource_sid)
      end

      unless (_sid = @sid).nil?
        return false if _sid.to_s.size > MAX_LENGTH_FOR_SID
        return false if _sid.to_s.size < MIN_LENGTH_FOR_SID
        return false if !PATTERN_FOR_SID.matches?(_sid)
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] account_sid Object to be assigned
    def account_sid=(new_value : String?)
      unless new_value.nil?
        OpenApi::PrimitiveValidator.validate_max_length("account_sid", new_value.to_s.size, MAX_LENGTH_FOR_ACCOUNT_SID)
        OpenApi::PrimitiveValidator.validate_min_length("account_sid", new_value.to_s.size, MIN_LENGTH_FOR_ACCOUNT_SID)
        OpenApi::PrimitiveValidator.validate_pattern("account_sid", new_value, PATTERN_FOR_ACCOUNT_SID)
      end

      @account_sid = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] assigned_add_on_sid Object to be assigned
    def assigned_add_on_sid=(new_value : String?)
      unless new_value.nil?
        OpenApi::PrimitiveValidator.validate_max_length("assigned_add_on_sid", new_value.to_s.size, MAX_LENGTH_FOR_ASSIGNED_ADD_ON_SID)
        OpenApi::PrimitiveValidator.validate_min_length("assigned_add_on_sid", new_value.to_s.size, MIN_LENGTH_FOR_ASSIGNED_ADD_ON_SID)
        OpenApi::PrimitiveValidator.validate_pattern("assigned_add_on_sid", new_value, PATTERN_FOR_ASSIGNED_ADD_ON_SID)
      end

      @assigned_add_on_sid = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] enabled Object to be assigned
    def enabled=(new_value : Bool?)
      @enabled = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] friendly_name Object to be assigned
    def friendly_name=(new_value : String?)
      @friendly_name = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] product_name Object to be assigned
    def product_name=(new_value : String?)
      @product_name = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] resource_sid Object to be assigned
    def resource_sid=(new_value : String?)
      unless new_value.nil?
        OpenApi::PrimitiveValidator.validate_max_length("resource_sid", new_value.to_s.size, MAX_LENGTH_FOR_RESOURCE_SID)
        OpenApi::PrimitiveValidator.validate_min_length("resource_sid", new_value.to_s.size, MIN_LENGTH_FOR_RESOURCE_SID)
        OpenApi::PrimitiveValidator.validate_pattern("resource_sid", new_value, PATTERN_FOR_RESOURCE_SID)
      end

      @resource_sid = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sid Object to be assigned
    def sid=(new_value : String?)
      unless new_value.nil?
        OpenApi::PrimitiveValidator.validate_max_length("sid", new_value.to_s.size, MAX_LENGTH_FOR_SID)
        OpenApi::PrimitiveValidator.validate_min_length("sid", new_value.to_s.size, MIN_LENGTH_FOR_SID)
        OpenApi::PrimitiveValidator.validate_pattern("sid", new_value, PATTERN_FOR_SID)
      end

      @sid = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] unique_name Object to be assigned
    def unique_name=(new_value : String?)
      @unique_name = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] uri Object to be assigned
    def uri=(new_value : String?)
      @uri = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@account_sid, @account_sid_present, @assigned_add_on_sid, @assigned_add_on_sid_present, @enabled, @enabled_present, @friendly_name, @friendly_name_present, @product_name, @product_name_present, @resource_sid, @resource_sid_present, @sid, @sid_present, @unique_name, @unique_name_present, @uri, @uri_present)
  end
end
