#  Twilio - Api
#
# This is the public Twilio REST API.
#
# The version of the OpenAPI document: 1.29.1
# Contact: support@twilio.com
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module Twilio
  class SipSipIpAccessControlListSipIpAddress
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Json

    # Optional properties

    # The unique id of the Account that is responsible for this resource.
    @[JSON::Field(key: "account_sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: account_sid.nil? && !account_sid_present?)]
    getter account_sid : String? = nil

    @[JSON::Field(ignore: true)]
    property? account_sid_present : Bool = false

    # An integer representing the length of the CIDR prefix to use with this IP address when accepting traffic. By default the entire IP address is used.
    @[JSON::Field(key: "cidr_prefix_length", type: Int32?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: cidr_prefix_length.nil? && !cidr_prefix_length_present?)]
    getter cidr_prefix_length : Int32? = nil

    @[JSON::Field(ignore: true)]
    property? cidr_prefix_length_present : Bool = false

    # The date that this resource was created, given as GMT in RFC 2822 format.
    @[JSON::Field(key: "date_created", type: Time?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: date_created.nil? && !date_created_present?, converter: Time::RFC2822Converter)]
    getter date_created : Time? = nil

    @[JSON::Field(ignore: true)]
    property? date_created_present : Bool = false

    # The date that this resource was last updated, given as GMT in RFC 2822 format.
    @[JSON::Field(key: "date_updated", type: Time?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: date_updated.nil? && !date_updated_present?, converter: Time::RFC2822Converter)]
    getter date_updated : Time? = nil

    @[JSON::Field(ignore: true)]
    property? date_updated_present : Bool = false

    # A human readable descriptive text for this resource, up to 64 characters long.
    @[JSON::Field(key: "friendly_name", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: friendly_name.nil? && !friendly_name_present?)]
    getter friendly_name : String? = nil

    @[JSON::Field(ignore: true)]
    property? friendly_name_present : Bool = false

    # The unique id of the IpAccessControlList resource that includes this resource.
    @[JSON::Field(key: "ip_access_control_list_sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: ip_access_control_list_sid.nil? && !ip_access_control_list_sid_present?)]
    getter ip_access_control_list_sid : String? = nil

    @[JSON::Field(ignore: true)]
    property? ip_access_control_list_sid_present : Bool = false

    # An IP address in dotted decimal notation from which you want to accept traffic. Any SIP requests from this IP address will be allowed by Twilio. IPv4 only supported today.
    @[JSON::Field(key: "ip_address", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: ip_address.nil? && !ip_address_present?)]
    getter ip_address : String? = nil

    @[JSON::Field(ignore: true)]
    property? ip_address_present : Bool = false

    # A 34 character string that uniquely identifies this resource.
    @[JSON::Field(key: "sid", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: sid.nil? && !sid_present?)]
    getter sid : String? = nil

    @[JSON::Field(ignore: true)]
    property? sid_present : Bool = false

    # The URI for this resource, relative to https://api.twilio.com
    @[JSON::Field(key: "uri", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: uri.nil? && !uri_present?)]
    getter uri : String? = nil

    @[JSON::Field(ignore: true)]
    property? uri_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @account_sid : String? = nil,
      @cidr_prefix_length : Int32? = nil,
      @date_created : Time? = nil,
      @date_updated : Time? = nil,
      @friendly_name : String? = nil,
      @ip_access_control_list_sid : String? = nil,
      @ip_address : String? = nil,
      @sid : String? = nil,
      @uri : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if _account_sid = @account_sid
        if _account_sid.to_s.size > 34
          invalid_properties.push("invalid value for \"account_sid\", the character length must be smaller than or equal to 34.")
        end

        if _account_sid.to_s.size < 34
          invalid_properties.push("invalid value for \"account_sid\", the character length must be great than or equal to 34.")
        end

        pattern = /^AC[0-9a-fA-F]{32}$/
        if _account_sid !~ pattern
          invalid_properties.push("invalid value for \"account_sid\", must conform to the pattern #{pattern}.")
        end
      end
      if _ip_access_control_list_sid = @ip_access_control_list_sid
        if _ip_access_control_list_sid.to_s.size > 34
          invalid_properties.push("invalid value for \"ip_access_control_list_sid\", the character length must be smaller than or equal to 34.")
        end

        if _ip_access_control_list_sid.to_s.size < 34
          invalid_properties.push("invalid value for \"ip_access_control_list_sid\", the character length must be great than or equal to 34.")
        end

        pattern = /^AL[0-9a-fA-F]{32}$/
        if _ip_access_control_list_sid !~ pattern
          invalid_properties.push("invalid value for \"ip_access_control_list_sid\", must conform to the pattern #{pattern}.")
        end
      end
      if _sid = @sid
        if _sid.to_s.size > 34
          invalid_properties.push("invalid value for \"sid\", the character length must be smaller than or equal to 34.")
        end

        if _sid.to_s.size < 34
          invalid_properties.push("invalid value for \"sid\", the character length must be great than or equal to 34.")
        end

        pattern = /^IP[0-9a-fA-F]{32}$/
        if _sid !~ pattern
          invalid_properties.push("invalid value for \"sid\", must conform to the pattern #{pattern}.")
        end
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      if _account_sid = @account_sid
        return false if _account_sid.to_s.size > 34
        return false if _account_sid.to_s.size < 34
        return false if _account_sid !~ /^AC[0-9a-fA-F]{32}$/
      end
      if _ip_access_control_list_sid = @ip_access_control_list_sid
        return false if _ip_access_control_list_sid.to_s.size > 34
        return false if _ip_access_control_list_sid.to_s.size < 34
        return false if _ip_access_control_list_sid !~ /^AL[0-9a-fA-F]{32}$/
      end
      if _sid = @sid
        return false if _sid.to_s.size > 34
        return false if _sid.to_s.size < 34
        return false if _sid !~ /^IP[0-9a-fA-F]{32}$/
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] account_sid Object to be assigned
    def account_sid=(account_sid : String?)
      if account_sid.nil?
        return @account_sid = nil
      end
      _account_sid = account_sid.not_nil!
      if _account_sid.to_s.size > 34
        raise ArgumentError.new("invalid value for \"account_sid\", the character length must be smaller than or equal to 34.")
      end

      if _account_sid.to_s.size < 34
        raise ArgumentError.new("invalid value for \"account_sid\", the character length must be great than or equal to 34.")
      end

      pattern = /^AC[0-9a-fA-F]{32}$/
      if _account_sid !~ pattern
        raise ArgumentError.new("invalid value for \"account_sid\", must conform to the pattern #{pattern}.")
      end

      @account_sid = account_sid
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] cidr_prefix_length Object to be assigned
    def cidr_prefix_length=(cidr_prefix_length : Int32?)
      if cidr_prefix_length.nil?
        return @cidr_prefix_length = nil
      end
      @cidr_prefix_length = cidr_prefix_length
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] date_created Object to be assigned
    def date_created=(date_created : Time?)
      if date_created.nil?
        return @date_created = nil
      end
      @date_created = date_created
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] date_updated Object to be assigned
    def date_updated=(date_updated : Time?)
      if date_updated.nil?
        return @date_updated = nil
      end
      @date_updated = date_updated
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] friendly_name Object to be assigned
    def friendly_name=(friendly_name : String?)
      if friendly_name.nil?
        return @friendly_name = nil
      end
      @friendly_name = friendly_name
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] ip_access_control_list_sid Object to be assigned
    def ip_access_control_list_sid=(ip_access_control_list_sid : String?)
      if ip_access_control_list_sid.nil?
        return @ip_access_control_list_sid = nil
      end
      _ip_access_control_list_sid = ip_access_control_list_sid.not_nil!
      if _ip_access_control_list_sid.to_s.size > 34
        raise ArgumentError.new("invalid value for \"ip_access_control_list_sid\", the character length must be smaller than or equal to 34.")
      end

      if _ip_access_control_list_sid.to_s.size < 34
        raise ArgumentError.new("invalid value for \"ip_access_control_list_sid\", the character length must be great than or equal to 34.")
      end

      pattern = /^AL[0-9a-fA-F]{32}$/
      if _ip_access_control_list_sid !~ pattern
        raise ArgumentError.new("invalid value for \"ip_access_control_list_sid\", must conform to the pattern #{pattern}.")
      end

      @ip_access_control_list_sid = ip_access_control_list_sid
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] ip_address Object to be assigned
    def ip_address=(ip_address : String?)
      if ip_address.nil?
        return @ip_address = nil
      end
      @ip_address = ip_address
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sid Object to be assigned
    def sid=(sid : String?)
      if sid.nil?
        return @sid = nil
      end
      _sid = sid.not_nil!
      if _sid.to_s.size > 34
        raise ArgumentError.new("invalid value for \"sid\", the character length must be smaller than or equal to 34.")
      end

      if _sid.to_s.size < 34
        raise ArgumentError.new("invalid value for \"sid\", the character length must be great than or equal to 34.")
      end

      pattern = /^IP[0-9a-fA-F]{32}$/
      if _sid !~ pattern
        raise ArgumentError.new("invalid value for \"sid\", must conform to the pattern #{pattern}.")
      end

      @sid = sid
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] uri Object to be assigned
    def uri=(uri : String?)
      if uri.nil?
        return @uri = nil
      end
      @uri = uri
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@account_sid, @account_sid_present, @cidr_prefix_length, @cidr_prefix_length_present, @date_created, @date_created_present, @date_updated, @date_updated_present, @friendly_name, @friendly_name_present, @ip_access_control_list_sid, @ip_access_control_list_sid_present, @ip_address, @ip_address_present, @sid, @sid_present, @uri, @uri_present)
  end
end
